import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className=''
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className=''>
					<div className=''>
						<Image
							src="/logo.svg"
							alt="WalletConnect Logo"
							height="32"
							width="203"
						/>
					</div>
					<div className=''>
						<div
							onClick={closeAll}
							className=''
						>
							<w3m-network-button />
						</div>
						<div
							onClick={closeAll}
							className=''
						>
							<w3m-button label="Connect" />
						</div>
						<div
							onClick={closeAll}
							className=''
						>
							<button>hello</button>
						</div>
					</div>
				</div>
			</header>
		</>
	);
}
